// Auto-reorder from par levels — Phase D #77.
//
// When an ingredient's stock drops below its lowStockThreshold AND it has
// a preferred marketplace supplier + product + reorderQty configured,
// this service submits a PO to top the stock back up. Every generated
// row is tagged autoGenerated=true so the merchant UI can badge it and
// let staff scan-and-cancel before the supplier acknowledges.
//
// Called after each sale-triggered stock deduction. Also exposed as a
// batch scanner so an admin "run now" button can rescan every eligible
// ingredient (e.g. after a big waste event).
//
// Key design choices:
//   1. FIRE-AND-FORGET at the caller. Errors are swallowed + logged so a
//      failure to draft a PO NEVER blocks the sale that triggered it.
//   2. COOLDOWN — 24h per ingredient. Prevents burst-sale spam. Only
//      blocks if there's still a live pre-shipped PO for the same SKU.
//   3. GROUPING — multiple below-par ingredients sharing a preferred
//      supplier are combined into ONE PO, not one per ingredient.
//   4. Server-authoritative pricing — unit price / minOrderQty / stepQty
//      re-read from the live SupplierProduct row (same rule as the
//      merchant cart flow) with volume-tier resolution.
//   5. Skips products whose supplier no longer has an accepted
//      relationship with this merchant, or whose product row went
//      inactive since it was configured.
//   6. Only touches the FIRST location for a tenant — multi-warehouse
//      auto-reorder is task #76 and will layer on later.
//
// Deliberately does NOT:
//   - Generate a payment link. Would require re-doing the KYB /
//     provider lookup path from the cart endpoint. Merchant can pay via
//     the same "Pay with card" surface the manual PO flow exposes; the
//     link fills in on demand from the detail page (v2 will inline it).

import { Prisma } from "@prisma/client";
import prisma from "@/lib/prisma";
import { createPoWithUniqueNumber } from "@/lib/marketplace-po-number";
import { effectiveUnitPriceCents } from "@/lib/supplier-price-tiers";

const COOLDOWN_HOURS = 24;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface AutoReorderResult {
  scanned: number;              // ingredients evaluated
  eligible: number;             // ingredients that passed all gates
  posCreated: number;           // number of draft/submitted POs
  posSubmitted: number;         // subset that were auto-submitted
  itemsOrdered: number;         // total line items across POs
  skipped: { ingredientName: string; reason: string }[];
  poNumbers: string[];
}

/**
 * Evaluate a specific list of ingredients (typically the ones a sale just
 * decremented). Cheap fast-path called by the recipe deducter.
 */
export async function evaluateIngredientsForReorder(
  tenantId: string,
  ingredientIds: string[]
): Promise<AutoReorderResult> {
  if (ingredientIds.length === 0) {
    return emptyResult();
  }
  return runAutoReorder(tenantId, { ingredientIds });
}

/**
 * Scan every auto-reorder-enabled ingredient for this tenant. Powers the
 * "run now" admin button and the (future) cron entry.
 */
export async function scanAndReorderForTenant(
  tenantId: string
): Promise<AutoReorderResult> {
  return runAutoReorder(tenantId, {});
}

// ---------------------------------------------------------------------------
// Core scanner
// ---------------------------------------------------------------------------

interface ScanOptions {
  ingredientIds?: string[];
}

async function runAutoReorder(
  tenantId: string,
  opts: ScanOptions
): Promise<AutoReorderResult> {
  const result = emptyResult();
  try {
    // Load candidates. Filter to enabled + fully-configured. The DB has
    // no XOR constraint here (we didn't add one — makes the migration
    // simpler); we enforce "all 3 preferred fields present" in code.
    const where: Prisma.IngredientWhereInput = {
      tenantId,
      autoReorderEnabled: true,
      isActive: true,
      preferredSupplierTenantId: { not: null },
      preferredSupplierProductId: { not: null },
      reorderQty: { not: null },
    };
    if (opts.ingredientIds && opts.ingredientIds.length > 0) {
      where.id = { in: opts.ingredientIds };
    }

    const candidates = await prisma.ingredient.findMany({
      where,
      select: {
        id: true,
        name: true,
        lowStockThreshold: true,
        reorderQty: true,
        preferredSupplierTenantId: true,
        preferredSupplierProductId: true,
        lastAutoReorderAt: true,
        preferredSupplierProduct: {
          select: {
            id: true,
            name: true,
            sku: true,
            unitLabel: true,
            wholesalePriceCents: true,
            minOrderQty: true,
            stepQty: true,
            isActive: true,
            variantAxes: true,
            supplierTenantId: true,
            priceTiers: {
              orderBy: { minQty: "asc" },
              select: { minQty: true, unitPriceCents: true },
            },
          },
        },
        locationInventory: {
          select: { locationId: true, currentStock: true },
        },
      },
    });

    result.scanned = candidates.length;

    // For each candidate, compute total stock across locations. v1 uses
    // aggregate stock across all locations against the single par level —
    // task #76 will make par per-location.
    type Draft = {
      ingredientId: string;
      ingredientName: string;
      productId: string;
      productName: string;
      productSku: string | null;
      unitLabel: string;
      unitPriceCents: number;
      minOrderQty: number;
      stepQty: number;
      qty: number;
      lineTotalCents: number;
      supplierTenantId: string;
    };

    // Group drafts by supplier so we can create one PO per supplier.
    const draftsBySupplier = new Map<string, Draft[]>();
    // Stamped lastAutoReorderAt is filled per-supplier inside the create
    // loop below — only ingredients that actually landed in a successful
    // PO get their cooldown updated.
    const stampedIngredientIds: string[] = [];

    for (const ing of candidates) {
      const totalStock = ing.locationInventory.reduce(
        (sum, li) => sum + Number(li.currentStock),
        0
      );
      const par = Number(ing.lowStockThreshold);
      if (totalStock >= par) {
        // Above par — nothing to do. NOT a "skipped" (it's normal state).
        continue;
      }

      // Cooldown gate. If we drafted in the last 24h, only re-draft when
      // that prior draft is no longer in DRAFT status (merchant cancelled
      // or submitted it) — checked below to save a round-trip when
      // possible.
      if (ing.lastAutoReorderAt) {
        const ageMs = Date.now() - ing.lastAutoReorderAt.getTime();
        if (ageMs < COOLDOWN_HOURS * 60 * 60 * 1000) {
          // Look for any live PO to this supplier for this SKU still in
          // pre-shipped status — if one exists, back off (the merchant
          // hasn't received it yet, no point stacking another one).
          const conflicting = await prisma.purchaseOrderItem.findFirst({
            where: {
              productId: ing.preferredSupplierProductId ?? undefined,
              purchaseOrder: {
                merchantTenantId: tenantId,
                supplierTenantId: ing.preferredSupplierTenantId ?? undefined,
                status: { in: ["SUBMITTED", "ACKNOWLEDGED"] },
              },
            },
            select: { id: true },
          });
          if (conflicting) {
            result.skipped.push({
              ingredientName: ing.name,
              reason: "Recent auto-reorder still pending — cooldown active",
            });
            continue;
          }
        }
      }

      const product = ing.preferredSupplierProduct;
      if (!product || !product.isActive) {
        result.skipped.push({
          ingredientName: ing.name,
          reason: "Preferred supplier product no longer active",
        });
        continue;
      }
      if (product.variantAxes.length > 0) {
        // v1: no auto-reorder for products with variants — merchant must
        // pick a specific variant. Variants have their own tier tables
        // and per-variant SKU handling that this v1 skips.
        result.skipped.push({
          ingredientName: ing.name,
          reason: "Preferred product has variants — pick a specific variant to auto-reorder",
        });
        continue;
      }

      // Round the requested qty up to the supplier's step and enforce
      // the minimum. Slightly over-order rather than under-order.
      const requestedQty = Number(ing.reorderQty ?? 0);
      const step = Math.max(1, product.stepQty || 1);
      const min = Math.max(1, product.minOrderQty || 1);
      let qty = Math.max(min, Math.ceil(requestedQty / step) * step);
      if (qty <= 0) qty = min;

      // Volume-tier pricing (Phase D #73).
      const tiers = product.priceTiers.map((t) => ({
        minQty: t.minQty,
        unitPriceCents: t.unitPriceCents,
      }));
      const unitPriceCents = effectiveUnitPriceCents(
        qty,
        product.wholesalePriceCents,
        tiers
      );

      const draft: Draft = {
        ingredientId: ing.id,
        ingredientName: ing.name,
        productId: product.id,
        productName: product.name,
        productSku: product.sku ?? null,
        unitLabel: product.unitLabel,
        unitPriceCents,
        minOrderQty: min,
        stepQty: step,
        qty,
        lineTotalCents: unitPriceCents * qty,
        supplierTenantId: product.supplierTenantId,
      };

      const bucket = draftsBySupplier.get(product.supplierTenantId) ?? [];
      bucket.push(draft);
      draftsBySupplier.set(product.supplierTenantId, bucket);
      result.eligible++;
    }

    if (draftsBySupplier.size === 0) {
      return result;
    }

    // Resolve the merchant's default (first) location + tenant currency
    // once. All auto-drafted POs ship to this address.
    const merchantTenant = await prisma.tenant.findUnique({
      where: { id: tenantId },
      select: { currency: true },
    });
    if (!merchantTenant) {
      throw new Error(`Tenant ${tenantId} not found while auto-reordering`);
    }

    const location = await prisma.location.findFirst({
      where: { tenantId },
      orderBy: { createdAt: "asc" },
      select: {
        id: true,
        name: true,
        address: true,
        city: true,
        province: true,
        postalCode: true,
        country: true,
        phone: true,
      },
    });
    if (!location) {
      throw new Error(`Tenant ${tenantId} has no location — cannot auto-reorder`);
    }
    const shippingAddress = {
      name: location.name,
      address: location.address || null,
      city: location.city || null,
      province: location.province || null,
      postalCode: location.postalCode || null,
      country: location.country,
      phone: location.phone || null,
    };

    // Per supplier: verify (or create implicitly-accepted) relationship
    // + create the PO.
    for (const [supplierTenantId, drafts] of draftsBySupplier) {
      try {
        const relationship = await prisma.supplierMerchantRelationship.findFirst({
          where: {
            supplierTenantId,
            merchantTenantId: tenantId,
            status: "ACTIVE",
          },
          select: { id: true },
        });
        if (!relationship) {
          // No active relationship = no auto-order. A merchant configuring
          // a preferred supplier they later paused/terminated is a stale
          // pointer; surface it, don't silently create one.
          drafts.forEach((d) => {
            result.skipped.push({
              ingredientName: d.ingredientName,
              reason: "No active relationship with the preferred supplier",
            });
          });
          continue;
        }

        const subtotalCents = drafts.reduce((s, d) => s + d.lineTotalCents, 0);
        const totalCents = subtotalCents; // no tax in v1

        // v1 always SUBMITs — the merchant can cancel any PO before the
        // supplier acknowledges. Keeping a DRAFT status out of the state
        // machine means we don't need to touch supplier queries or add a
        // "submit draft" flow. autoGenerated=true flags the row so the
        // list UI can badge + let merchants scan-and-cancel quickly.
        const po = await createPoWithUniqueNumber((poNumber) =>
          prisma.purchaseOrder.create({
            data: {
              supplierTenantId,
              merchantTenantId: tenantId,
              merchantLocationId: location.id,
              relationshipId: relationship.id,
              poNumber,
              status: "SUBMITTED",
              currency: merchantTenant.currency,
              subtotalCents,
              taxCents: 0,
              totalCents,
              shippingAddress,
              notesToSupplier:
                "Auto-generated from par-level rules. Cancel within a few hours if this wasn't wanted.",
              autoGenerated: true,
              items: {
                create: drafts.map((d) => ({
                  productId: d.productId,
                  productSku: d.productSku,
                  productName: d.productName,
                  unitLabel: d.unitLabel,
                  unitPriceCents: d.unitPriceCents,
                  qty: d.qty,
                  lineTotalCents: d.lineTotalCents,
                })),
              },
            },
            select: { id: true, poNumber: true, status: true },
          })
        );

        result.posCreated++;
        result.posSubmitted++;
        result.itemsOrdered += drafts.length;
        result.poNumbers.push(po.poNumber);
        drafts.forEach((d) => stampedIngredientIds.push(d.ingredientId));
        console.log(
          `[AUTO-REORDER] ${po.poNumber} (${po.status}) for tenant ${tenantId} → supplier ${supplierTenantId}, ${drafts.length} item(s)`
        );
      } catch (err: any) {
        console.error(
          `[AUTO-REORDER] Failed to create PO for supplier ${supplierTenantId}:`,
          err?.message || err
        );
        drafts.forEach((d) => {
          result.skipped.push({
            ingredientName: d.ingredientName,
            reason: "PO creation failed — see server log",
          });
        });
      }
    }

    if (stampedIngredientIds.length > 0) {
      await prisma.ingredient.updateMany({
        where: { id: { in: stampedIngredientIds } },
        data: { lastAutoReorderAt: new Date() },
      });
    }

    return result;
  } catch (err: any) {
    console.error("[AUTO-REORDER] Fatal error:", err?.message || err);
    return result;
  }
}

function emptyResult(): AutoReorderResult {
  return {
    scanned: 0,
    eligible: 0,
    posCreated: 0,
    posSubmitted: 0,
    itemsOrdered: 0,
    skipped: [],
    poNumbers: [],
  };
}
