// GET /api/tenants/[tenantId]/marketplace/orders
// Lists purchase orders THIS merchant has placed across all suppliers.
//
// Query params:
//   ?status=SUBMITTED       — filter by exact status
//   ?supplierId=<uuid>      — filter by supplier
//   ?search=xyz             — matches PO number
//
// Mirror of the supplier-side list endpoint (see
// /api/supplier/orders/route.ts) but from the buyer's perspective.

import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { validateRequest } from "@/lib/api-middleware";
import { unreadMessageCounts } from "@/lib/po-messages";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ tenantId: string }> }
) {
  try {
    const { tenantId } = await params;

    const auth = await validateRequest(request, tenantId, "POS_STAFF");
    if (!auth.success) return auth.response;

    const { searchParams } = new URL(request.url);
    const status = searchParams.get("status");
    const supplierId = searchParams.get("supplierId");
    const search = searchParams.get("search")?.trim();

    const where: any = { merchantTenantId: tenantId };
    if (status) where.status = status;
    if (supplierId) where.supplierTenantId = supplierId;
    if (search) {
      where.poNumber = { contains: search, mode: "insensitive" };
    }

    const orders = await prisma.purchaseOrder.findMany({
      where,
      orderBy: { submittedAt: "desc" },
      take: 200,
      select: {
        id: true,
        poNumber: true,
        status: true,
        currency: true,
        totalCents: true,
        submittedAt: true,
        acknowledgedAt: true,
        shippedAt: true,
        deliveredAt: true,
        cancelledAt: true,
        expectedDeliveryAt: true,
        // Phase C #67: payment surface for the list row
        paymentStatus: true,
        paymentLinkUrl: true,
        paidAt: true,
        // Phase D #77: badge auto-generated POs
        autoGenerated: true,
        supplierTenant: {
          select: {
            id: true,
            name: true,
            supplierProfile: { select: { displayName: true } },
          },
        },
        _count: { select: { items: true } },
      },
    });

    const rawCounts = await prisma.purchaseOrder.groupBy({
      by: ["status"],
      where: { merchantTenantId: tenantId },
      _count: true,
    });
    const counts = Object.fromEntries(rawCounts.map((c) => [c.status, c._count]));

    // Unread supplier-message counts per PO — one grouped query.
    const unreadMap = await unreadMessageCounts(
      orders.map((o) => o.id),
      "MERCHANT"
    );

    return NextResponse.json({
      success: true,
      orders: orders.map((o) => ({
        ...o,
        supplierName:
          o.supplierTenant.supplierProfile?.displayName || o.supplierTenant.name,
        unreadMessageCount: unreadMap.get(o.id) || 0,
      })),
      counts,
      total: orders.length,
    });
  } catch (error: any) {
    console.error("[MERCHANT-ORDERS] GET error:", error);
    return NextResponse.json({ error: "Failed to load orders" }, { status: 500 });
  }
}
